<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BT_Start</name>
   <tag></tag>
   <elementGuidId>65469c74-6108-4cf4-997c-f008a0bc9410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button</value>
   </webElementProperties>
</WebElementEntity>
